
def Router():

    text = '''// TODO:empty\n'''
    text += '''\n'''
    text += '''import {{ request, response, Router }} from 'express';\n'''
    text += '''\n'''
    text += '''import AuthUser from '../middlewares/AuthUser.middlewares';\n'''
    text += '''\n'''
    text += '''const {MODELLOWER}Router = Router();\n'''
    text += '''\n'''
    text += '''{MODELLOWER}Router.use(AuthUser);\n'''
    text += '''\n\n'''

    text += '''{MODELLOWER}Router.post('/', async (request, response) => {{\n'''
    text += '''    try {{\n'''
    text += '''        response.status(500).json({{message:`${{request.method}} is empty`}})\n'''
    text += '''    }} catch (err) {{\n'''
    text += '''        response.status(500).json({{message:`${{request.method}} is empty`}})\n'''
    text += '''    }}\n'''
    text += '''}});\n'''
    text += '''\n'''
    text += '''{MODELLOWER}Router.put('/', async (request, response) => {{\n'''
    text += '''    try {{\n'''
    text += '''        response.status(500).json({{message:`${{request.method}} is empty`}})\n'''
    text += '''    }} catch (err) {{\n'''
    text += '''        response.status(500).json({{message:`${{request.method}} is empty`}})\n'''
    text += '''    }}\n'''
    text += '''}});\n'''
    text += '''\n'''
    text += '''{MODELLOWER}Router.delete('/', async (request, response) => {{\n'''
    text += '''    try {{\n'''
    text += '''        response.status(500).json({{message:`${{request.method}} is empty`}})\n'''
    text += '''    }} catch (err) {{\n'''
    text += '''        response.status(500).json({{message:`${{request.method}} is empty`}})\n'''
    text += '''    }}\n'''
    text += '''}});\n'''
    text += '''\n'''
    text += '''{MODELLOWER}Router.get('/', async (request, response) => {{\n'''
    text += '''    try {{\n'''
    text += '''        response.status(500).json({{message:`${{request.method}} is empty`}})\n'''
    text += '''    }} catch (err) {{\n'''
    text += '''        response.status(500).json({{message:`${{request.method}} is empty`}})\n'''
    text += '''    }}\n'''
    text += '''}});\n'''
    text += '''\n\n'''
    text += '''export default {MODELLOWER}Router;\n'''

    

    return text